/**
 * Command/device Tools
 *
 * This file exports all tools in the command/device category.
 * Auto-generated by the MCP server generator.
 */

export { getCameraInfo, getCameraInfoMetadata } from './get-camera-info.js';
export { listAlarmsDevices, listAlarmsDevicesMetadata } from './list-alarms-devices.js';
export { listViewingStationDevices, listViewingStationDevicesMetadata } from './list-viewing-station-devices.js';
