/**
 * Product/camera Tools
 *
 * This file exports all tools in the product/camera category.
 * Auto-generated by the MCP server generator.
 */

export { createDashboardWidgetTrends, createDashboardWidgetTrendsMetadata } from './create-dashboard-widget-trends.js';
export { createLicensePlateOfInterest, createLicensePlateOfInterestMetadata } from './create-license-plate-of-interest.js';
export { createLicensePlateOfInterestBulkOperation, createLicensePlateOfInterestBulkOperationMetadata } from './create-license-plate-of-interest-bulk-operation.js';
export { createOccupancyTrendsMqttConfig, createOccupancyTrendsMqttConfigMetadata } from './create-occupancy-trends-mqtt-config.js';
export { createPersonOfInterest, createPersonOfInterestMetadata } from './create-person-of-interest.js';
export { deleteLicensePlateOfInterest, deleteLicensePlateOfInterestMetadata } from './delete-license-plate-of-interest.js';
export { deleteLicensePlateOfInterestBulkOperation, deleteLicensePlateOfInterestBulkOperationMetadata } from './delete-license-plate-of-interest-bulk-operation.js';
export { deletePersonOfInterest, deletePersonOfInterestMetadata } from './delete-person-of-interest.js';
export { getCameraAudioConfiguration, getCameraAudioConfigurationMetadata } from './get-camera-audio-configuration.js';
export { getCameraFootageUrl, getCameraFootageUrlMetadata } from './get-camera-footage-url.js';
export { getCameraSnapshot, getCameraSnapshotMetadata } from './get-camera-snapshot.js';
export { getCloudBackupConfiguration, getCloudBackupConfigurationMetadata } from './get-cloud-backup-configuration.js';
export { getDashboardOccupancyTrends, getDashboardOccupancyTrendsMetadata } from './get-dashboard-occupancy-trends.js';
export { getFootageStream, getFootageStreamMetadata } from './get-footage-stream.js';
export { getFootageToken, getFootageTokenMetadata } from './get-footage-token.js';
export { getLicensePlateOfInterest, getLicensePlateOfInterestMetadata } from './get-license-plate-of-interest.js';
export { getMaxObjectCounts, getMaxObjectCountsMetadata } from './get-max-object-counts.js';
export { getObjectCounts, getObjectCountsMetadata } from './get-object-counts.js';
export { getOccupancyTrends, getOccupancyTrendsMetadata } from './get-occupancy-trends.js';
export { getOccupancyTrendsCameras, getOccupancyTrendsCamerasMetadata } from './get-occupancy-trends-cameras.js';
export { getPersonOfInterest, getPersonOfInterestMetadata } from './get-person-of-interest.js';
export { getThumbnailLatest, getThumbnailLatestMetadata } from './get-thumbnail-latest.js';
export { getThumbnailLink, getThumbnailLinkMetadata } from './get-thumbnail-link.js';
export { listLprImages, listLprImagesMetadata } from './list-lpr-images.js';
export { listLprTimestampsView, listLprTimestampsViewMetadata } from './list-lpr-timestamps-view.js';
export { updateCameraAudioConfiguration, updateCameraAudioConfigurationMetadata } from './update-camera-audio-configuration.js';
export { updateCloudBackupConfiguration, updateCloudBackupConfigurationMetadata } from './update-cloud-backup-configuration.js';
export { updateLicensePlateOfInterest, updateLicensePlateOfInterestMetadata } from './update-license-plate-of-interest.js';
export { updatePersonOfInterest, updatePersonOfInterestMetadata } from './update-person-of-interest.js';
