/**
 * Command/site Tools
 *
 * This file exports all tools in the command/site category.
 * Auto-generated by the MCP server generator.
 */

export { getAlarmsSites, getAlarmsSitesMetadata } from './get-alarms-sites.js';
export { getGuestSite, getGuestSiteMetadata } from './get-guest-site.js';
