/**
 * Product/sensor Tools
 *
 * This file exports all tools in the product/sensor category.
 * Auto-generated by the MCP server generator.
 */

export { getSensorData, getSensorDataMetadata } from './get-sensor-data.js';
