/**
 * MCP Server Tools
 *
 * This file exports all tools organized by category.
 * Auto-generated by the MCP server generator.
 */

import { registerToolFromMetadata, ToolRegistry, RegisteredTool } from '../tool-registry.js';
import {
  getNotifications, getNotificationsMetadata,
  listSensorAlerts, listSensorAlertsMetadata,
  listProductEvents, listProductEventsMetadata,
} from './command/alert/index.js';
import {
  getAuditLogs, getAuditLogsMetadata,
} from './command/audit-log/index.js';
import {
  getLoginApiToken, getLoginApiTokenMetadata,
} from './command/authentication/index.js';
import {
  listAlarmsDevices, listAlarmsDevicesMetadata,
  getCameraInfo, getCameraInfoMetadata,
  listViewingStationDevices, listViewingStationDevicesMetadata,
} from './command/device/index.js';
import {
  getAlarmsSites, getAlarmsSitesMetadata,
  getGuestSite, getGuestSiteMetadata,
} from './command/site/index.js';
import {
  getUser, getUserMetadata,
  createUser, createUserMetadata,
  updateUser, updateUserMetadata,
  deleteUser, deleteUserMetadata,
} from './command/user/index.js';
import {
  listAccessGroups, listAccessGroupsMetadata,
  getAccessGroup, getAccessGroupMetadata,
  createAccessGroup, createAccessGroupMetadata,
  deleteAccessGroup, deleteAccessGroupMetadata,
  updateAccessGroupUser, updateAccessGroupUserMetadata,
  deleteAccessGroupUser, deleteAccessGroupUserMetadata,
  getAccessMembers, getAccessMembersMetadata,
  getAccessUser, getAccessUserMetadata,
  activateActivateBleMethod, activateActivateBleMethodMetadata,
  deactivateDeactivateBleMethod, deactivateDeactivateBleMethodMetadata,
  updateAccessEndDate, updateAccessEndDateMetadata,
  updateAccessUserPin, updateAccessUserPinMetadata,
  deleteAccessUserPin, deleteAccessUserPinMetadata,
  inviteSendPassAppInvite, inviteSendPassAppInviteMetadata,
  getProfilePhoto, getProfilePhotoMetadata,
  updateProfilePhoto, updateProfilePhotoMetadata,
  deleteProfilePhoto, deleteProfilePhotoMetadata,
  activateActivateRemoteUnlock, activateActivateRemoteUnlockMetadata,
  deactivateDeactivateRemoteUnlock, deactivateDeactivateRemoteUnlockMetadata,
  updateAccessStartDate, updateAccessStartDateMetadata,
  createAccessCard, createAccessCardMetadata,
  deleteAccessCard, deleteAccessCardMetadata,
  activateAccessCardActivate, activateAccessCardActivateMetadata,
  deactivateAccessCardDeactivate, deactivateAccessCardDeactivateMetadata,
  createLicensePlate, createLicensePlateMetadata,
  deleteLicensePlate, deleteLicensePlateMetadata,
  activateLicensePlateActivate, activateLicensePlateActivateMetadata,
  deactivateLicensePlateDeactivate, deactivateLicensePlateDeactivateMetadata,
  postMfaCodeViewV1, postMfaCodeViewV1Metadata,
  deleteMfaCodeViewV1, deleteMfaCodeViewV1Metadata,
  getAccessLevel, getAccessLevelMetadata,
  createAccessLevel, createAccessLevelMetadata,
  getAccessLevelDetail, getAccessLevelDetailMetadata,
  updateAccessLevelDetail, updateAccessLevelDetailMetadata,
  deleteAccessLevelDetail, deleteAccessLevelDetailMetadata,
  createAccessLevelSchedule, createAccessLevelScheduleMetadata,
  getAccessLevelSchedule, getAccessLevelScheduleMetadata,
  updateAccessLevelSchedule, updateAccessLevelScheduleMetadata,
  deleteAccessLevelSchedule, deleteAccessLevelScheduleMetadata,
  unlockAccessAdminApiUnlock, unlockAccessAdminApiUnlockMetadata,
  getAccessDoorExceptionCalendars, getAccessDoorExceptionCalendarsMetadata,
  createAccessDoorExceptionCalendars, createAccessDoorExceptionCalendarsMetadata,
  getAccessDoorExceptionCalendar, getAccessDoorExceptionCalendarMetadata,
  updateAccessDoorExceptionCalendar, updateAccessDoorExceptionCalendarMetadata,
  deleteAccessDoorExceptionCalendar, deleteAccessDoorExceptionCalendarMetadata,
  createAccessDoorExceptions, createAccessDoorExceptionsMetadata,
  getAccessDoorException, getAccessDoorExceptionMetadata,
  updateAccessDoorException, updateAccessDoorExceptionMetadata,
  deleteAccessDoorException, deleteAccessDoorExceptionMetadata,
  unlockAccessUserApiUnlock, unlockAccessUserApiUnlockMetadata,
  getAccessDoorInformation, getAccessDoorInformationMetadata,
  listAccessScenarioList, listAccessScenarioListMetadata,
  activateAccessScenarioActivate, activateAccessScenarioActivateMetadata,
  createAccessScenarioRelease, createAccessScenarioReleaseMetadata,
  listAccessEvents, listAccessEventsMetadata,
  deleteFaceUnlockDisableExternalUser, deleteFaceUnlockDisableExternalUserMetadata,
  unlockFaceUnlockCopyUserPhotoExternalUser, unlockFaceUnlockCopyUserPhotoExternalUserMetadata,
  unlockFaceUnlockInviteExternalUser, unlockFaceUnlockInviteExternalUserMetadata,
  unlockFaceUnlockUploadPhotoExternalUser, unlockFaceUnlockUploadPhotoExternalUserMetadata,
  deleteFaceUnlockDisableUser, deleteFaceUnlockDisableUserMetadata,
  unlockFaceUnlockCopyUserPhotoUser, unlockFaceUnlockCopyUserPhotoUserMetadata,
  unlockFaceUnlockInviteUser, unlockFaceUnlockInviteUserMetadata,
  unlockFaceUnlockUploadPhotoUser, unlockFaceUnlockUploadPhotoUserMetadata,
} from './product/access/index.js';
import {
  getDashboardOccupancyTrends, getDashboardOccupancyTrendsMetadata,
  listLprImages, listLprImagesMetadata,
  getLicensePlateOfInterest, getLicensePlateOfInterestMetadata,
  createLicensePlateOfInterest, createLicensePlateOfInterestMetadata,
  updateLicensePlateOfInterest, updateLicensePlateOfInterestMetadata,
  deleteLicensePlateOfInterest, deleteLicensePlateOfInterestMetadata,
  createLicensePlateOfInterestBulkOperation, createLicensePlateOfInterestBulkOperationMetadata,
  deleteLicensePlateOfInterestBulkOperation, deleteLicensePlateOfInterestBulkOperationMetadata,
  listLprTimestampsView, listLprTimestampsViewMetadata,
  getMaxObjectCounts, getMaxObjectCountsMetadata,
  getObjectCounts, getObjectCountsMetadata,
  createOccupancyTrendsMqttConfig, createOccupancyTrendsMqttConfigMetadata,
  getOccupancyTrends, getOccupancyTrendsMetadata,
  getCameraAudio, getCameraAudioMetadata,
  createCameraAudio, createCameraAudioMetadata,
  getCloudBackup, getCloudBackupMetadata,
  createCloudBackup, createCloudBackupMetadata,
  getHistoryUrl, getHistoryUrlMetadata,
  getCameraSnapshot, getCameraSnapshotMetadata,
  getThumbnailLatest, getThumbnailLatestMetadata,
  getThumbnailLink, getThumbnailLinkMetadata,
  getFootageToken, getFootageTokenMetadata,
  getOccupancyTrendsCameras, getOccupancyTrendsCamerasMetadata,
  getPersonOfInterest, getPersonOfInterestMetadata,
  createPersonOfInterest, createPersonOfInterestMetadata,
  updatePersonOfInterest, updatePersonOfInterestMetadata,
  deletePersonOfInterest, deletePersonOfInterestMetadata,
  getFootageStream, getFootageStreamMetadata,
  createDashboardWidgetTrends, createDashboardWidgetTrendsMetadata,
} from './product/camera/index.js';
import {
  listDenyList, listDenyListMetadata,
  createDenyList, createDenyListMetadata,
  deleteDenyList, deleteDenyListMetadata,
  getVisit, getVisitMetadata,
  getGuestEvent, getGuestEventMetadata,
  createGuestEvent, createGuestEventMetadata,
  getGuestSingleEvent, getGuestSingleEventMetadata,
  deleteGuestSingleEvent, deleteGuestSingleEventMetadata,
  getGuestType, getGuestTypeMetadata,
  getHost, getHostMetadata,
} from './product/guest/index.js';
import {
  getHelixEvent, getHelixEventMetadata,
  createHelixEvent, createHelixEventMetadata,
  updateHelixEvent, updateHelixEventMetadata,
  deleteHelixEvent, deleteHelixEventMetadata,
  searchHelixEvent, searchHelixEventMetadata,
  listHelixEventTypes, listHelixEventTypesMetadata,
  createHelixEventType, createHelixEventTypeMetadata,
  updateHelixEventType, updateHelixEventTypeMetadata,
  deleteHelixEventType, deleteHelixEventTypeMetadata,
} from './product/helix/index.js';
import {
  getSensorData, getSensorDataMetadata,
} from './product/sensor/index.js';

export const allTools = [
  // - command/alert: 3 tools
  registerToolFromMetadata(getNotificationsMetadata, getNotifications),
  registerToolFromMetadata(listSensorAlertsMetadata, listSensorAlerts),
  registerToolFromMetadata(listProductEventsMetadata, listProductEvents),
  // - command/audit-log: 1 tools
  registerToolFromMetadata(getAuditLogsMetadata, getAuditLogs),
  // - command/authentication: 1 tools
  registerToolFromMetadata(getLoginApiTokenMetadata, getLoginApiToken),
  // - command/device: 3 tools
  registerToolFromMetadata(listAlarmsDevicesMetadata, listAlarmsDevices),
  registerToolFromMetadata(getCameraInfoMetadata, getCameraInfo),
  registerToolFromMetadata(listViewingStationDevicesMetadata, listViewingStationDevices),
  // - command/site: 2 tools
  registerToolFromMetadata(getAlarmsSitesMetadata, getAlarmsSites),
  registerToolFromMetadata(getGuestSiteMetadata, getGuestSite),
  // - command/user: 4 tools
  registerToolFromMetadata(getUserMetadata, getUser),
  registerToolFromMetadata(createUserMetadata, createUser),
  registerToolFromMetadata(updateUserMetadata, updateUser),
  registerToolFromMetadata(deleteUserMetadata, deleteUser),
  // - product/access: 63 tools
  registerToolFromMetadata(listAccessGroupsMetadata, listAccessGroups),
  registerToolFromMetadata(getAccessGroupMetadata, getAccessGroup),
  registerToolFromMetadata(createAccessGroupMetadata, createAccessGroup),
  registerToolFromMetadata(deleteAccessGroupMetadata, deleteAccessGroup),
  registerToolFromMetadata(updateAccessGroupUserMetadata, updateAccessGroupUser),
  registerToolFromMetadata(deleteAccessGroupUserMetadata, deleteAccessGroupUser),
  registerToolFromMetadata(getAccessMembersMetadata, getAccessMembers),
  registerToolFromMetadata(getAccessUserMetadata, getAccessUser),
  registerToolFromMetadata(activateActivateBleMethodMetadata, activateActivateBleMethod),
  registerToolFromMetadata(deactivateDeactivateBleMethodMetadata, deactivateDeactivateBleMethod),
  registerToolFromMetadata(updateAccessEndDateMetadata, updateAccessEndDate),
  registerToolFromMetadata(updateAccessUserPinMetadata, updateAccessUserPin),
  registerToolFromMetadata(deleteAccessUserPinMetadata, deleteAccessUserPin),
  registerToolFromMetadata(inviteSendPassAppInviteMetadata, inviteSendPassAppInvite),
  registerToolFromMetadata(getProfilePhotoMetadata, getProfilePhoto),
  registerToolFromMetadata(updateProfilePhotoMetadata, updateProfilePhoto),
  registerToolFromMetadata(deleteProfilePhotoMetadata, deleteProfilePhoto),
  registerToolFromMetadata(activateActivateRemoteUnlockMetadata, activateActivateRemoteUnlock),
  registerToolFromMetadata(deactivateDeactivateRemoteUnlockMetadata, deactivateDeactivateRemoteUnlock),
  registerToolFromMetadata(updateAccessStartDateMetadata, updateAccessStartDate),
  registerToolFromMetadata(createAccessCardMetadata, createAccessCard),
  registerToolFromMetadata(deleteAccessCardMetadata, deleteAccessCard),
  registerToolFromMetadata(activateAccessCardActivateMetadata, activateAccessCardActivate),
  registerToolFromMetadata(deactivateAccessCardDeactivateMetadata, deactivateAccessCardDeactivate),
  registerToolFromMetadata(createLicensePlateMetadata, createLicensePlate),
  registerToolFromMetadata(deleteLicensePlateMetadata, deleteLicensePlate),
  registerToolFromMetadata(activateLicensePlateActivateMetadata, activateLicensePlateActivate),
  registerToolFromMetadata(deactivateLicensePlateDeactivateMetadata, deactivateLicensePlateDeactivate),
  registerToolFromMetadata(postMfaCodeViewV1Metadata, postMfaCodeViewV1),
  registerToolFromMetadata(deleteMfaCodeViewV1Metadata, deleteMfaCodeViewV1),
  registerToolFromMetadata(getAccessLevelMetadata, getAccessLevel),
  registerToolFromMetadata(createAccessLevelMetadata, createAccessLevel),
  registerToolFromMetadata(getAccessLevelDetailMetadata, getAccessLevelDetail),
  registerToolFromMetadata(updateAccessLevelDetailMetadata, updateAccessLevelDetail),
  registerToolFromMetadata(deleteAccessLevelDetailMetadata, deleteAccessLevelDetail),
  registerToolFromMetadata(createAccessLevelScheduleMetadata, createAccessLevelSchedule),
  registerToolFromMetadata(getAccessLevelScheduleMetadata, getAccessLevelSchedule),
  registerToolFromMetadata(updateAccessLevelScheduleMetadata, updateAccessLevelSchedule),
  registerToolFromMetadata(deleteAccessLevelScheduleMetadata, deleteAccessLevelSchedule),
  registerToolFromMetadata(unlockAccessAdminApiUnlockMetadata, unlockAccessAdminApiUnlock),
  registerToolFromMetadata(getAccessDoorExceptionCalendarsMetadata, getAccessDoorExceptionCalendars),
  registerToolFromMetadata(createAccessDoorExceptionCalendarsMetadata, createAccessDoorExceptionCalendars),
  registerToolFromMetadata(getAccessDoorExceptionCalendarMetadata, getAccessDoorExceptionCalendar),
  registerToolFromMetadata(updateAccessDoorExceptionCalendarMetadata, updateAccessDoorExceptionCalendar),
  registerToolFromMetadata(deleteAccessDoorExceptionCalendarMetadata, deleteAccessDoorExceptionCalendar),
  registerToolFromMetadata(createAccessDoorExceptionsMetadata, createAccessDoorExceptions),
  registerToolFromMetadata(getAccessDoorExceptionMetadata, getAccessDoorException),
  registerToolFromMetadata(updateAccessDoorExceptionMetadata, updateAccessDoorException),
  registerToolFromMetadata(deleteAccessDoorExceptionMetadata, deleteAccessDoorException),
  registerToolFromMetadata(unlockAccessUserApiUnlockMetadata, unlockAccessUserApiUnlock),
  registerToolFromMetadata(getAccessDoorInformationMetadata, getAccessDoorInformation),
  registerToolFromMetadata(listAccessScenarioListMetadata, listAccessScenarioList),
  registerToolFromMetadata(activateAccessScenarioActivateMetadata, activateAccessScenarioActivate),
  registerToolFromMetadata(createAccessScenarioReleaseMetadata, createAccessScenarioRelease),
  registerToolFromMetadata(listAccessEventsMetadata, listAccessEvents),
  registerToolFromMetadata(deleteFaceUnlockDisableExternalUserMetadata, deleteFaceUnlockDisableExternalUser),
  registerToolFromMetadata(unlockFaceUnlockCopyUserPhotoExternalUserMetadata, unlockFaceUnlockCopyUserPhotoExternalUser),
  registerToolFromMetadata(unlockFaceUnlockInviteExternalUserMetadata, unlockFaceUnlockInviteExternalUser),
  registerToolFromMetadata(unlockFaceUnlockUploadPhotoExternalUserMetadata, unlockFaceUnlockUploadPhotoExternalUser),
  registerToolFromMetadata(deleteFaceUnlockDisableUserMetadata, deleteFaceUnlockDisableUser),
  registerToolFromMetadata(unlockFaceUnlockCopyUserPhotoUserMetadata, unlockFaceUnlockCopyUserPhotoUser),
  registerToolFromMetadata(unlockFaceUnlockInviteUserMetadata, unlockFaceUnlockInviteUser),
  registerToolFromMetadata(unlockFaceUnlockUploadPhotoUserMetadata, unlockFaceUnlockUploadPhotoUser),
  // - product/camera: 29 tools
  registerToolFromMetadata(getDashboardOccupancyTrendsMetadata, getDashboardOccupancyTrends),
  registerToolFromMetadata(listLprImagesMetadata, listLprImages),
  registerToolFromMetadata(getLicensePlateOfInterestMetadata, getLicensePlateOfInterest),
  registerToolFromMetadata(createLicensePlateOfInterestMetadata, createLicensePlateOfInterest),
  registerToolFromMetadata(updateLicensePlateOfInterestMetadata, updateLicensePlateOfInterest),
  registerToolFromMetadata(deleteLicensePlateOfInterestMetadata, deleteLicensePlateOfInterest),
  registerToolFromMetadata(createLicensePlateOfInterestBulkOperationMetadata, createLicensePlateOfInterestBulkOperation),
  registerToolFromMetadata(deleteLicensePlateOfInterestBulkOperationMetadata, deleteLicensePlateOfInterestBulkOperation),
  registerToolFromMetadata(listLprTimestampsViewMetadata, listLprTimestampsView),
  registerToolFromMetadata(getMaxObjectCountsMetadata, getMaxObjectCounts),
  registerToolFromMetadata(getObjectCountsMetadata, getObjectCounts),
  registerToolFromMetadata(createOccupancyTrendsMqttConfigMetadata, createOccupancyTrendsMqttConfig),
  registerToolFromMetadata(getOccupancyTrendsMetadata, getOccupancyTrends),
  registerToolFromMetadata(getCameraAudioMetadata, getCameraAudio),
  registerToolFromMetadata(createCameraAudioMetadata, createCameraAudio),
  registerToolFromMetadata(getCloudBackupMetadata, getCloudBackup),
  registerToolFromMetadata(createCloudBackupMetadata, createCloudBackup),
  registerToolFromMetadata(getHistoryUrlMetadata, getHistoryUrl),
  registerToolFromMetadata(getCameraSnapshotMetadata, getCameraSnapshot),
  registerToolFromMetadata(getThumbnailLatestMetadata, getThumbnailLatest),
  registerToolFromMetadata(getThumbnailLinkMetadata, getThumbnailLink),
  registerToolFromMetadata(getFootageTokenMetadata, getFootageToken),
  registerToolFromMetadata(getOccupancyTrendsCamerasMetadata, getOccupancyTrendsCameras),
  registerToolFromMetadata(getPersonOfInterestMetadata, getPersonOfInterest),
  registerToolFromMetadata(createPersonOfInterestMetadata, createPersonOfInterest),
  registerToolFromMetadata(updatePersonOfInterestMetadata, updatePersonOfInterest),
  registerToolFromMetadata(deletePersonOfInterestMetadata, deletePersonOfInterest),
  registerToolFromMetadata(getFootageStreamMetadata, getFootageStream),
  registerToolFromMetadata(createDashboardWidgetTrendsMetadata, createDashboardWidgetTrends),
  // - product/guest: 10 tools
  registerToolFromMetadata(listDenyListMetadata, listDenyList),
  registerToolFromMetadata(createDenyListMetadata, createDenyList),
  registerToolFromMetadata(deleteDenyListMetadata, deleteDenyList),
  registerToolFromMetadata(getVisitMetadata, getVisit),
  registerToolFromMetadata(getGuestEventMetadata, getGuestEvent),
  registerToolFromMetadata(createGuestEventMetadata, createGuestEvent),
  registerToolFromMetadata(getGuestSingleEventMetadata, getGuestSingleEvent),
  registerToolFromMetadata(deleteGuestSingleEventMetadata, deleteGuestSingleEvent),
  registerToolFromMetadata(getGuestTypeMetadata, getGuestType),
  registerToolFromMetadata(getHostMetadata, getHost),
  // - product/helix: 9 tools
  registerToolFromMetadata(getHelixEventMetadata, getHelixEvent),
  registerToolFromMetadata(createHelixEventMetadata, createHelixEvent),
  registerToolFromMetadata(updateHelixEventMetadata, updateHelixEvent),
  registerToolFromMetadata(deleteHelixEventMetadata, deleteHelixEvent),
  registerToolFromMetadata(searchHelixEventMetadata, searchHelixEvent),
  registerToolFromMetadata(listHelixEventTypesMetadata, listHelixEventTypes),
  registerToolFromMetadata(createHelixEventTypeMetadata, createHelixEventType),
  registerToolFromMetadata(updateHelixEventTypeMetadata, updateHelixEventType),
  registerToolFromMetadata(deleteHelixEventTypeMetadata, deleteHelixEventType),
  // - product/sensor: 1 tools
  registerToolFromMetadata(getSensorDataMetadata, getSensorData),
];

// ============================================================================
// REGISTRATION FUNCTIONS
// ============================================================================
/**
 * Register all tools with a ToolRegistry instance
 */
export function registerAllTools(registry: ToolRegistry): void {
  registry.registerAll(allTools);
}
/**
* Get the count of available tools
*/
export function getToolCount() {
  return allTools.length;
}
/**
* Get tools grouped by category
*/
export function getToolsByCategory(): Record<string, RegisteredTool[]> {
  const categories: Record<string, RegisteredTool[]> = {};
  for (const tool of allTools) {
    const category = tool.metadata?.category || 'uncategorized';
    if (!categories[category]) {
      categories[category] = [];
    }
    categories[category].push(tool);
  }
  return categories;
}
